---
seed_jobdsl: |
  job("seed") {
      properties {
          authorizeProjectProperty {
              strategy {
                  triggeringUsersAuthorizationStrategy()
              }
          }
      }
      scm {
          git(
          'https://github.com/joejstuart/ci-pipeline.git',
          'jobDsl',
          {node -> node / 'extensions' << '' })
      }
      steps {
          dsl {
              external('jobs/*.groovy')
              removeAction('DELETE')
              ignoreExisting()
              additionalClasspath('src')
          }
      }
  }
  queue("seed")
