---
seed_jobdsl: |
  pipelineJob("seed") {
      description('This job is automagically generated.')
      definition {
          cpsScm {
              scm {
                  git('https://github.com/joejstuart/ci-pipeline.git')
              }
          }
      }
  }
