---
seed_jobdsl: |
  job("seed") {
      scm {
          git('https://github.com/joejstuart/ci-pipeline.git')
      }
      steps {
          dsl {
              external('jobs/*.groovy')
              removeAction('DELETE')
              ignoreExisting()
              additionalClasspath('src/org/centos/dsl')
          }
      }
  }
  queue("seed")
