apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: elasticsearch
  annotations:
    openshift.io/display-name: elasticsearch
    description: |-
              contra elasticsearch template
    iconClass: icon-jenkins
    tags: instant-app,elasticsearch
    template.openshift.io/long-description: Elasticsearch container
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://docs.openshift.org/latest
    template.openshift.io/support-url: https://access.redhat.com
parameters:
- name: STORAGE_SIZE
  value: 10Gi
  description: The size of the persistent storage for Elasticsearch
- name: REPO_URL
  value: https://github.com/joejstuart/ci-pipeline.git
  description: The dockerfile repo url
- name: REPO_CONTEXTDIR
  description: The sub-directory inside the repository.
  value: config/Dockerfiles/elasticsearch
- name: REPO_REF
  description: The git ref or tag to use for customization.
  value: es
- name: ELASTICSEARCH_VERSION
  value: 5.6.8
  description: The es version
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: elasticsearch
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: elasticsearch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: elasticsearch:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: ELASTICSEARCH_VERSION
            value: ${ELASTICSEARCH_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: elasticsearch-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      route: elasticsearch
    name: elasticsearch
    creationTimestamp:
  spec:
    port:
      targetPort: api-http
    to:
      kind: Service
      name: elasticsearch
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      metrics: elasticsearch
    name: elasticsearch
  spec:
    ports:
    - name: api-http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: admin-http
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      metrics: elasticsearch
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      metrics: elasticsearch
    name: elasticsearch
  spec:
    strategy:
        type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - elasticsearch
        from:
          kind: ImageStreamTag
          name: elasticsearch:latest
          namespace: continuous-infra
          lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    selector:
      metrics: elasticsearch
    template:
      metadata:
        creationTimestamp: null
        labels:
          metrics: elasticsearch
      spec:
        containers:
        - env:
          - name: ELASTICSEARCH_VERSION
            value: ${ELASTICSEARCH_VERSION}
          image: elasticsearch:stable
          imagePullPolicy: Always
          name: elasticsearch
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: _cluster/health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: _cluster/health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
  status: {}
labels:
  template: elasticsearch
