cluster.name: contra-es

node.name: ${HOSTNAME}

network.host: _site_

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: ["elasticsearch-discovery"]
discovery.zen.ping_timeout: 15s

logger.org.elasticsearch.http: trace
