cluster.name: contra-es

node.name: ${HOSTNAME}

network.host: _site_

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
