network.host: _site_

cluster.name: contra-es

# Uncomment the following lines for a production cluster deployment
transport.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: elasticsearch-discovery
#discovery.zen.minimum_master_nodes: 0
